### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by calypsoup** [IllusorySoftware/UnrealModUnlocker-Public#1]
Can't you build the .dll and put it into releases ? its too much hassle to get the .dll
Severity    Code    Description    Project    File    Line    Suppression State
Error    LNK1181    cannot open input file 'C:\Users\GHFear\source\repos\CURLTEST\curl\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel\lib\libcurl_a.lib'    UMU    D:\UnrealModUnlocker-Public-main\UMU\LINK    1

**Comment by systemsiteseason** [comment]
download curl source in https://curl.se/download.html
run file buildconf.bat
use x64 native for vs
dir to winbuild curl
type "nmake /f Makefile.vc mode=static"

done!

**Comment by calypsoup** [comment]
Hello again ! thank you i got it to work but issue is this dll does not work with "Scarlet Nexus", Game loads files that is already in .pak files without having to use .pak but there is addional file types game system in the game .ucas .utoc which contains sketal meshes and character textures etc. Could you please look into it? and thank you making for this tool

My discord is "Telli#5371" if you need any file from the game and stuff so on i can directly send !

**Comment by systemsiteseason** [comment]
sorry. Zen Loader or I/O Store is keyword you can search in google. you can read code in source ue4 4.25 or 4.26. let research it.

**Comment by GHFear** [comment]
> Can't you build the .dll and put it into releases ? its too much hassle to get the .dll
> Severity Code Description Project File Line Suppression State
> Error LNK1181 cannot open input file 'C:\Users\GHFear\source\repos\CURLTEST\curl\builds\libcurl-vc-x64-release-static-ipv6-sspi-schannel\lib\libcurl_a.lib' UMU D:\UnrealModUnlocker-Public-main\UMU\LINK 1

This issue has been fixed.
Curl should not have been needed since it's never used.
So I removed it from the project + added a tutorial for finding sigs real easy with IDA Pro.
